# Use `allow` to specify which dependencies to maintain

version: 2
updates:
  - package-ecosystem: "npm" #npm
    directory: "/"
    schedule:
      interval: "daily"
    allow:
      # Allow direct updates for all packages
      - dependency-type: "all"
    labels:
      - "npm"
      - "dependencies"
      - "dependabot"

  - package-ecosystem: "composer" #composer
    directory: "/"
    schedule:
      interval: "daily"
    allow:
      #  Allow direct updates for all packages
      - dependency-type: "all"
    labels:
      - "composer"
      - "dependencies"
      - "dependabot"

  - package-ecosystem: "pip" #python
    directory: "/addons/falcon-bridge-shim/requirements.txt"
    schedule:
      interval: "daily"
    allow:
      #  Allow direct updates for all packages
      - dependency-type: "all"
    labels:
      - "python"
      - "dependencies"
      - "dependabot"
 
  # Maintain dependencies for GitHub Actions
  - package-ecosystem: "github-actions" #github-actions
    directory: "/"
    schedule:
      interval: "daily"
    allow:
      #  Allow direct updates for all packages
      - dependency-type: "all"
    labels:
      - "github_actions"
      - "dependencies"
      - "dependabot"

  - package-ecosystem: "bundler"
    directory: "/"
    schedule:
      interval: "daily"
    allow:
      #  Allow direct updates for all packages
      - dependency-type: "all"
    labels:
      - "bundler"
      - "dependencies"
      - "dependabot"

  - package-ecosystem: "cargo"
    directory: "/"
    schedule:
      interval: "daily"
    allow:
      #  Allow direct updates for all packages
      - dependency-type: "all"
    labels:
      - "cargo"
      - "dependencies"
      - "dependabot"

  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "daily"
    allow:
      #  Allow direct updates for all packages
      - dependency-type: "all"
    labels:
      - "docker"
      - "dependencies"
      - "dependabot"
  
  - package-ecosystem: "gomod"
    directory: "/"
    schedule:
      interval: "daily"
    allow:
      #  Allow direct updates for all packages
      - dependency-type: "all"
    labels:
      - "golang"
      - "dependencies"
      - "dependabot"

  - package-ecosystem: "gradle"
    directory: "/"
    schedule:
      interval: "daily"
    allow:
      #  Allow direct updates for all packages
      - dependency-type: "all"
    labels:
      - "gradle"
      - "dependencies"
      - "dependabot"

  - package-ecosystem: "maven"
    directory: "/"
    schedule:
      interval: "daily"
    allow:
      #  Allow direct updates for all packages
      - dependency-type: "all"
    labels:
      - "maven"
      - "dependencies"
      - "dependabot"

  - package-ecosystem: "pub"
    directory: "/"
    schedule:
      interval: "daily"
    allow:
      #  Allow direct updates for all packages
      - dependency-type: "all"
    labels:
      - "pub"
      - "dependencies"
      - "dependabot"

  - package-ecosystem: "terraform"
    directory: "/"
    schedule:
      interval: "daily"
    allow:
      #  Allow direct updates for all packages
      - dependency-type: "all"
    labels:
      - "terraform"
      - "dependencies"
      - "dependabot"
