# Use `allow` to specify which dependencies to maintain

version: 2
enable-beta-ecosystems: true
updates:
  - package-ecosystem: "npm" #npm
    directory: "/"
    schedule:
      interval: "daily"
    allow:
      # Allow direct updates for all packages
      - dependency-type: "direct"
    labels:
      - "npm"
      - "dependencies"
      - "dependabot"

  - package-ecosystem: "composer" #composer
    directory: "/"
    schedule:
      interval: "daily"
    allow:
      #  Allow direct updates for all packages
      - dependency-type: "direct"
    labels:
      - "composer"
      - "dependencies"
      - "dependabot"

  - package-ecosystem: "pip" #python
    directory: "/"
    schedule:
      interval: "daily"
    allow:
      #  Allow direct updates for all packages
      - dependency-type: "direct"
    labels:
      - "python"
      - "dependencies"
      - "dependabot"   

  # Maintain dependencies for GitHub Actions
  - package-ecosystem: "github-actions" #github-actions
    directory: "/"
    schedule:
      interval: "daily"
    allow:
      #  Allow direct updates for all packages
      - dependency-type: "direct"
    labels:
      - "github_actions"
      - "dependencies"
      - "dependabot"
 
  - package-ecosystem: "beta-ecosystem"
    directory: "/"
    schedule:
      interval: "daily"
    allow:
      #  Allow direct updates for all packages
      - dependency-type: "direct"
    labels:
      - "beta_ecosystem"
      - "dependencies"
      - "dependabot"
 
  - package-ecosystem: "bundler"
    directory: "/"
    schedule:
      interval: "daily"
    allow:
      #  Allow direct updates for all packages
      - dependency-type: "direct"
    labels:
      - "bundler"
      - "dependencies"
      - "dependabot"
      
  - package-ecosystem: "cargo"
    directory: "/"
    schedule:
      interval: "daily"
    allow:
      #  Allow direct updates for all packages
      - dependency-type: "direct"
    labels:
      - "cargo"
      - "dependencies"
      - "dependabot"

  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "daily"
    allow:
      #  Allow direct updates for all packages
      - dependency-type: "direct"
    labels:
      - "docker"
      - "dependencies"
      - "dependabot"
  - package-ecosystem: "gomod"
    directory: "/"
    schedule:
      interval: "daily"
    allow:
      #  Allow direct updates for all packages
      - dependency-type: "direct"
    labels:
      - "golang"
      - "dependencies"
      - "dependabot"
  
  - package-ecosystem: "gradle"
    directory: "/"
    schedule:
      interval: "daily"
    allow:
      #  Allow direct updates for all packages
      - dependency-type: "direct"
    labels:
      - "gradle"
      - "dependencies"
      - "dependabot"
 
